#!/bin/bash 

# Environment Variables for Django sessions
# These Environment variables will be referenced in your django settings
#  file, the default being settings.py. Doing things this way allows you
#  to keep your project in a public repo without exposing your credentials

# IMPORTANT! DO NOT PUSH TO A PUBLIC git REPO AFTER FILLING THIS IN!!

export DJANGO_DB=''
export DJANGO_DB_USER=''
export DJANGO_DB_PWD=''
export DJANGO_SECRET_KEY=''
export DJANGO_AUTH_SUPERUSER=''
export DJANGO_AUTH_SUPERUSER_PWD=''
