#!/bin/bash 

# The sole purpose of this file is to make it easier to
#  push to kiln hosted repos while using long pseudorandom
#  passwords

# IMPORTANT! DO NOT PUSH TO A PUBLIC git REPO AFTER FILLING THIS IN!!

export KILN_USER=''
export KILN_PWD=''
